### ISSUE TITLE
More chip style overrides

### ISSUE THREAD

**Issue by c-moss-talk** [raynor85/react-native-material-selectize#10]
Correct me if I'm wrong, but currently it seems the text color and the icon color of the chip are both not overridable using `chipIconStyle` and `chipStyle`. Since the chip component has 5 different subcomponents could it be better to just pass a chipStyle object with each subcomponent as a key? Like so:
```
chipStyle = {
  root: {},
  container: {},
  text: {},
  iconWrapper: {},
  icon: {},
} 
```
Or do you feel like at this point you'd just be supplying your own component instead? If not, I can submit a PR.

**Comment by raynor85** [comment]
That's a good concern, but due to the simplistic nature of the Chip component, I feel like passing a custom component would be better.

**Comment by raynor85** [comment]
Although, since you're offering, I would be happy to merge your PR if you are so kind to work on it.

**Comment by c-moss-talk** [comment]
no time
