### ISSUE TITLE
How to load chips from database ?

### ISSUE THREAD

**Issue by arudrakalyan** [raynor85/react-native-material-selectize#2]
Hi, I am working on the edit screen of my application.  Is there any way to show chips from the array of strings that am getting from the database?

**Comment by raynor85** [comment]
You have to pass the prop `items` in the format specified in the docs: https://github.com/raynor85/react-native-material-selectize#items
How you retrieve data from the server and how you parse it is really up to your application architecture and your use case.

**Comment by arudrakalyan** [comment]
As I understand from the documentation and given example,  Items will show the list of data available to select from the data. Please correct me if am wrong.In my application am using this component in 'add and edit' screens. In add screen am able to select the data from the suggestion dropdown but not able to show the same in edit screen as chips format. My doubt is, how to parse the data from state and show as chips. So that users can remove select new items from the drop-down.

**Comment by raynor85** [comment]
So the question is about the possibility of rendering chips when the component mounts, it that right? Unfortunately, there is no such option yet, but it should be provided. Let me work on that and I will provide that capability.

**Comment by raynor85** [comment]
selectedItem prop added to allow chip rendering when the component loads.
https://github.com/raynor85/react-native-material-selectize/commit/dda73add74c87cdbc3f79bce8310d1bade13d5c6
