### ISSUE TITLE
Overlay text

### ISSUE THREAD

**Issue by piranna** [raynor85/react-native-material-selectize#3]
https://github.com/raynor85/react-native-material-selectize/blob/6d43dadcbffecad07d16eec081525ef757938eaf/src/react-native-selectize.js#L316-L320

I've found that an overlay text is being added while writting the text of a new chip. Don't know if it's purpossed for Android or iOS, but by using `react-native-web` it looks a bit ugly. Could you be able to clarify the purposse of that, and if so if it could be removed (maybe by an optional flag)?

**Comment by raynor85** [comment]
Example without hidden Text hack
![withouthiddenfield](https://user-images.githubusercontent.com/5817333/34879279-967596be-f7a4-11e7-819e-e9e79d96b615.gif)
Example with hidden Text hack (as it should be)
![withhiddenfield](https://user-images.githubusercontent.com/5817333/34879292-a7626772-f7a4-11e7-8167-29ecf9da7d76.gif)

**Comment by piranna** [comment]
I see... yes, maybe the `minWidth` would be a better option. In my case, since it's being used internally an HTML `input` tag that's the reason it's showed duplicated (and in fact, the `Text` node it's shown on over the input, not below as your example). I'll try to take a look and see if I can be able to fix it, or at least to add the option. Thanks! :-)

**Comment by piranna** [comment]
I have done a quick check and with `react-native-web` the text field automatically expands and move to the next line if text is too long, and when removed some characters it goes back to the previous line, that I think it's the expected behaviour (both for me and you :-) ). Thinking on this, seems that's because HTML by default use the flow layout while React and ReactNative use flex layout by design, so probably that's the reason you needed to do the over-enginering hack. I think there are some modules that implement flow layout, so it could be used in that case so it would be fixed everywhere, how do you see it? :-)

**Comment by raynor85** [comment]
autoReflow property added that defines whether the text should reflow to the new line if there is no enough space. Default is true

**Comment by piranna** [comment]
Great! :-) when this will be available in npm?

**Comment by raynor85** [comment]
It's already available.

**Comment by piranna** [comment]
Thank you! :-D
