### ISSUE TITLE
Feature Request: Simple onChange() callback prop

### ISSUE THREAD

**Issue by grailian** [raynor85/react-native-material-selectize#5]
Hello!

I think it would be very convenient to add an `onChange` prop to `<Selectize />`.
Here is my desired used case:

```
<Selectize
    label={this.props.displayName}
    itemId="value"
    items={this.props.fields}
    selectedItems={this.state.selected}
    onChange={(selected) => this.setState({ selected )}
/>
```

It looks like this could be achieved by adding this line:   
`this.props.onChange(selectedItems.result.map(id => selectedItems.entities.item[id]));`

to the `_onChipClose` and `_selectItem` functions.

**Comment by raynor85** [comment]
@BukhariMuslim #4 breaks the emailValidation example. I would love to merge it, but backwards compatibility must be guaranteed. @grailian if you don't mind, can you please add this in your PR? Thanks

**Comment by raynor85** [comment]
```onChangeSelectedItems``` props has been added with d61ca89b916979e3a377740afbeb742e377c31f9
