### ISSUE TITLE
`keyboardShouldPersistTaps` prop required of `ScrollView` parent

### ISSUE THREAD

**Issue by ehegnes** [raynor85/react-native-material-selectize#6]
When `Selectize` is a child of a `ScrollView`, the `ScrollView`'s `keyboardShouldPersistTaps` prop must be set to either `handled` or `always` for dropdown completion to work properly.

This is the case in the example project, but this detail is not listed anywhere in the documentation. It took me a couple of hours to discover that this was the culprit. Perhaps having this detail mentioned in the README or elsewhere would help others.

**Comment by raynor85** [comment]
Feel free to do a pr for that. I’ll merge it
