### ISSUE TITLE
SyntaxError: Invalid regular expression: missing ) when type "\"

### ISSUE THREAD

**Issue by BukhariMuslim** [raynor85/react-native-material-selectize#9]
I try to replicate your example on [this snack](https://snack.expo.io/rJ0h0keUm). Everything was going fine before I type "\\", then suddenly error occurred.

![image](https://user-images.githubusercontent.com/7993729/44055281-1961e560-9f6f-11e8-8701-d7df092ddf28.png)

**Comment by raynor85** [comment]
Thank you for pointing it out. Your solution is legit and I will create a PR soon.

**Comment by raynor85** [comment]
Closed by https://github.com/raynor85/react-native-material-selectize/tree/v1.11.2
